# Generated by Django 5.1.1 on 2024-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_remove_exam_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='answerexam',
            name='answer',
            field=models.CharField(max_length=5),
        ),
    ]
