# Generated by Django 5.1.1 on 2024-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_alter_answerchoice_answer_alter_answerexam_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
