# Generated by Django 5.1.1 on 2024-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_username', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_username', models.CharField(max_length=100)),
                ('teacher_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
