# Generated by Django 5.1.1 on 2024-10-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('teacher_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.teacher')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.section'),
        ),
    ]
