# Generated by Django 5.1.1 on 2024-10-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_section_student_student_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_username',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_username',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
